### ISSUE TITLE
ERROR in ./node_modules/cipher-base/index.js and ERROR in ./node_modules/hash-base/index.js

### ISSUE THREAD

**Issue by cstodor** [hapinessjs/ng-universal-transfer-http#20]
I've installed the hapinessjs into my Angular 6 which is using Universal SSR to avoid duplicate HttpClient requests on the client, but I get this error when I try to build the application in for production:

ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'src\node_modules\stream-browserify' in '\node_modules\cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'src\node_modules\stream-browserify' in 'node_modules\hash-base'

Can someone tell me what am I doing wrong? I followed the tutorial from here: https://github.com/hapinessjs/ng-universal-transfer-http/blob/master/projects/ng-universal-transfer-http/README.md

**Comment by njl07** [comment]
Hi @cstodor thanks to use this module and to solve your problem, follow the [tutorial](https://github.com/hapinessjs/ng-universal-transfer-http/blob/master/projects/ng-universal-transfer-http/README.md#polyfills) to add polyfills and works fine after
